---
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Creating EC2 instances
      amazon.aws.ec2_instance:
        name: "{{ item.name }}"
        key_name: "NexusKey"
        instance_type: t2.micro
        security_group: default
        region: us-east-1
        aws_access_key: "{{ec2_access_key}}"
        aws_secret_key: "{{ec2_secret_key}}" 
        network:
          assign_public_ip: true
        image_id: "{{ item.image }}"
        tags:
          Environment: "{{ item.name }}"
      loop:
        - { image: "ami-01b799c439fd5516a", name: "manage-node-1"  }
        - { image: "ami-04b70fa74e45c3917", name: "manage-node-2"  }
        - { image: "ami-04b70fa74e45c3917", name: "manage-node-3"  }
